services:
  api:
    build: ./fidc_api
    container_name: fidc_api
    command: python main.py
    ports:
      - "5000:5000"
    env_file:
      - .env
    depends_on:
      - db
      - redis
      - minio
    volumes:
      - ./fidc_api:/app
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health" ]
      interval: 30s
      timeout: 10s
      retries: 5

  worker:
    build: ./fidc_api
    container_name: fidc_worker
    command: celery -A app.workers.tasks worker --loglevel=INFO
    depends_on:
      - redis
      - db
    env_file:
      - .env
    volumes:
      - ./fidc_api:/app
    restart: always

  db:
    image: postgres:15
    container_name: fidc_postgres
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7
    container_name: fidc_redis
    restart: always
    ports:
      - "6379:6379"

  minio:
    image: minio/minio:latest
    container_name: fidc_minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data

volumes:
  postgres_data:
  minio_data: